### ISSUE TITLE
About Discretized Gaussian Mixture Likelihoods?

### ISSUE THREAD

**Issue by smileformylove** [ZhengxueCheng/Learned-Image-Compression-with-GMM-and-Attention#4]
Thanks for your paper and code!

I doubt the code for Discretized Gaussian Mixture Likelihoods, where I find the noise in code(network.py) at 371 line , it doesn't match the description in paper as eq.8. Since when we test(compress) an image, the inputs y_hat is just an intger with np.int operation. So the code at line 375 is redundant and misses the goal for discretized operation.

**Comment by ZhengxueCheng** [comment]
Thank you very much for your comment:)
Lines 419-447 are corresponding to likelihoods calculation as Eq. (8) during training, but I comment them during inference. It matches the description, because noise is just added to get approximated quantized y_tilde or y_hat, and Eq.(8) estimates rate for y_hat, instead of y. 
But, you are correct that Line 375 is redundant, because I found round is already in Line 509 of compress function and already np.int in decompress function. Anyway, it should not affect decoding or other results. 


> Thanks for your paper and code!
> 
> I doubt the code for Discretized Gaussian Mixture Likelihoods, where I find the noise in code(network.py) at 371 line , it doesn't match the description in paper as eq.8. Since when we test(compress) an image, the inputs y_hat is just an intger with np.int operation. So the code at line 375 is redundant and misses the goal for discretized operation.
