### ISSUE TITLE
About mask and pad size?

### ISSUE THREAD

**Issue by smileformylove** [ZhengxueCheng/Learned-Image-Compression-with-GMM-and-Attention#5]
Hi, sorry for asking question again :(

pad_size in network.py(589 line) is 2, and we extract y_mean_values/y_variances_values/y_probs_values(616/617/618 line) with pad_size, I think it's right when we start the masked_conv2d. However when the paddings of  y_hat_value run out, we here use all the values from y_hat_value, not zero from paddings, here  using pad_size(589 line) is out of place to estimate the mean and variance!!

And I also notice the question#3, I wonder the parallel operation between training and testing. Since we may feed the whole y_hat into the mask CNN and get its estimation when training. However the extracted y_hat around h_idx:h_idx+kernel w_idx:w_idx+kernel are used when testing. But you may train the network  different from what I describe!

**Comment by ZhengxueCheng** [comment]
Hi, thanks for your question.
If I understand your question correctly, this padding is just for acceleration. Because mask conv is only related to (5,5) windowed y_hat, then we don't necessary feed the whole size of y_hat to the entropy_parameter part. 
For example, y_hat and phi have a size of [1, 32, 48, N], after padding at two sides,  y_hat and phi will have a size of [1, 2+ 32+2, 2+48+2, N], referring to https://numpy.org/doc/1.18/reference/generated/numpy.pad.html. Then we always extract a small crop from them, i.e. extracted_y, extracted_phi having a size of 5x5 as Line 603 and 604, and only feed 5x5 size to network to calculate y_mean, y_variance, y_probs, which also have a size of 5x5. Then we take the center of them for probability estimation as Line 616/617/618. Actually it is similar as valid padding of convolution. 
BTW, you can ignore this padding if you would like to feed the whole y_hat into the mask CNN.
Let me know if you have further questions.


> Hi, sorry for asking question again :(
> 
> pad_size in network.py(589 line) is 2, and we extract y_mean_values/y_variances_values/y_probs_values(616/617/618 line) with pad_size, I think it's right when we start the masked_conv2d. However when the paddings of y_hat_value run out, we here use all the values from y_hat_value, not zero from paddings, here using pad_size(589 line) is out of place to estimate the mean and variance!!
> 
> And I also notice the question#3, I wonder the parallel operation between training and testing. Since we may feed the whole y_hat into the mask CNN and get its estimation when training. However the extracted y_hat around h_idx:h_idx+kernel w_idx:w_idx+kernel are used when testing. But you may train the network different from what I describe!

**Comment by smileformylove** [comment]
> Actually it is similar as valid padding of convolution.

Yeah, when it is like valid padding, it's all right! I just confuse the padding at mask CNN is SAME padding, but now I understand it! Thank you very much! 

And I notice your another work about lossless compression (https://arxiv.org/pdf/2002.01657.pdf). Could you give the detail about the ratio of bits-rate in lossy part and the last residual part?

**Comment by ZhengxueCheng** [comment]
> And I notice your another work about lossless compression (https://arxiv.org/pdf/2002.01657.pdf). Could you give the detail about the ratio of bits-rate in lossy part and the last residual part?

Hi, I checked results of our ICASSP'20 paper. Here is the detailed data for Table 2.
dataset | x_bit    | y_bit     | z_bit     | total
CLICP   | 1.4419 | 1.2638 | 0.0205 | 2.726
CLICM  | 1.3799 | 1.2580 | 0.0207 | 2.659
Kodak   | 1.3423 | 1.2755  | 0.0199 | 2.638
So, you can think the lossy part accounts for around 50% and last residual part accounts for the remaining 50%.
