### ISSUE TITLE
In network.py, why do you separate "phi" and pad it when you are encoding y?

### ISSUE THREAD

**Issue by consistent1997** [ZhengxueCheng/Learned-Image-Compression-with-GMM-and-Attention#6]
Sorry for bothering you, Prof. Cheng. When I read your code, I have two questions. Firstly, now that you have adopted entropy bottleneck in tensorflow_compression package to encode z or decode string, why did you choose rangecoder package to encode y or decode string? Why didn't you continue using entropy model to complete the next encoding and decoding process? Secondly, why do you separate "phi" and pad it when you are encoding y? What's the function of phi (phi is gotten by a hyper_synthesis function)?

**Comment by ZhengxueCheng** [comment]
Hi, thanks for your questions:)
First, this is just our implementation code last year and at that time tensorflow_compression package did not release the conditional entropy model for y yet. Now you can use both if you want.  
Second, this separation and padding operations are just for acceleration. Because mask conv is only related to a 5x5 windowed y_hat, then we don't necessary feed the whole size of y_hat and phi to the entropy_parameter part. So we separate them and always extract a small 5x5 crop from them, i.e. extracted_y, extracted_phi having a size of 5x5 as Line 603 and 604, and only feed 5x5 size to network to calculate y_mean, y_variance, y_probs, which also have a size of 5x5. Then we take the center of them for probability estimation as Line 616/617/618. Of course, you can ignore this padding if you would like to feed the whole phi and y_hat into the mask CNN, and in that case, we don't need to separate phi. Yes, phi is the output of a hyper_synthesis function. Let me know if you have further questions.

> Sorry for bothering you, Prof. Cheng. When I read your code, I have two questions. Firstly, now that you have adopted entropy bottleneck in tensorflow_compression package to encode z or decode string, why did you choose rangecoder package to encode y or decode string? Why didn't you continue using entropy model to complete the next encoding and decoding process? Secondly, why do you separate "phi" and pad it when you are encoding y? What's the function of phi (phi is gotten by a hyper_synthesis function)?

**Comment by consistent1997** [comment]
Thanks for your answers! I think I have got it!
